// Arquivo temporário para salvar o initialState correto
const initialState = {
  nome: '',
  sexo: '',
  data_nascimento: '',
  email: '',
  telefone: '',
  cpf: '',
  rg: '',
  cep: '',
  logradouro: '',
  numero: '',
  complemento: '',
  bairro: '',
  cidade: '',
  uf: '',
  convenio_id: '',
  numero_carteirinha: '',
  validade_carteira: '',
  profissao: '',
  estado_civil: '',
  observacoes: '',
  ativo: true,
  responsavel_nome: '',
  responsavel_telefone: '',
  responsavel_parentesco: '',
  responsavel_cpf: '',
  documentos: [],
};
